name: photo_editor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  nb_utils: ^7.0.3
  firebase_crashlytics: ^4.0.1
  firebase_core: ^3.1.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  device_info_plus: ^10.1.0
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  image_gallery_saver: ^2.0.3
  image: ^4.2.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  share: ^2.0.4
  package_info: ^2.0.2
  http: ^1.2.1
  glass_kit: ^4.0.1
  path_provider: ^2.1.3
  zoom_widget: ^2.0.1
  screenshot: ^2.5.0
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.0
  image_cropper: ^7.0.4
  image_picker: ^1.1.2
  video_trimmer: ^3.0.1
  font_awesome_flutter: ^10.7.0
  flutter_vector_icons: ^2.0.0
  flutter_native_image: ^0.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/frame/
    - images/stickers/
    - assets/fonts/
    - images/collegeMaker/
    - images/text_box/

  fonts:
    - family: Neon
      fonts:
        - asset: assets/fonts/neon.ttf
    - family: NeonCity
      fonts:
        - asset: assets/fonts/neoncity.otf
    - family: NeonLights
      fonts:
        - asset: assets/fonts/neonlights.ttf
